# Generated by Django 2.1.5 on 2019-02-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_gallery',
            name='category',
            field=models.CharField(choices=[('development', 'development'), ('design', 'design'), ('photography', 'photography')], default='development', max_length=255),
        ),
    ]
