# Generated by Django 2.1.5 on 2019-02-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_auto_20190202_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_gallery',
            name='category',
            field=models.CharField(choices=[('web development', 'web development'), ('web design', 'web design'), ('photography', 'photography')], default='web development', max_length=255),
        ),
    ]
