# Generated by Django 2.2.4 on 2019-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_remove_backgroundimages_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimages',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
